version: "3.3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.34
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=your_vpn_provider
      - VPN_TYPE=your_vpn_type
      - OPENVPN_USER=your_openvpn_user
      - OPENVPN_PASSWORD=your_openvpn_password
      - WIREGUARD_PRIVATE_KEY=your_wireguard_private_key
      - WIREGUARD_ADDRESS=your_wireguard_address
      - WIREGUARD_PUBLIC_KEY=your_wireguard_public_key
      - TZ=Asia/Kolkata
      - UPDATER_PERIOD=24h
    ports:
      - "80:80"
      - "8080:8080"
    restart: on-failure
  
  app:
    build: .
    network_mode: "service:gluetun"  # Use VPN network from gluetun container
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"  # This will bind to the same ports as gluetun, ensure there's no conflict
      
